version: "3"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      # MYSQL_ROOT_PASSWORD: your_password_here
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: bootcamp098
      MYSQL_DATABASE: employeeDB
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
